# Generated by Django 3.0.8 on 2020-08-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_international_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internationalelements',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
