# Generated by Django 3.0.8 on 2020-08-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200801_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internationalelements',
            name='img',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
