# Generated by Django 3.0.8 on 2020-08-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20200801_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internationalelements',
            name='img',
            field=models.FileField(blank=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
