# Generated by Django 3.0.8 on 2020-08-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20200801_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('heading_private', models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок Частные занятия')),
                ('text_private', models.TextField(blank=True, null=True, verbose_name='Текст Частные занятия')),
                ('heading_group', models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок Групповые занятия')),
                ('text_group', models.TextField(blank=True, null=True, verbose_name='Текст Групповые занятия')),
                ('img', models.ImageField(upload_to='', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Страница Занятий',
                'verbose_name_plural': 'Страница Занятий',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='StudyElements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('heading', models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Элементы страницы Занятия',
                'verbose_name_plural': 'Элементы страницы Занятия',
                'ordering': ['pk'],
            },
        ),
    ]
