# Generated by Django 3.0.8 on 2020-08-01 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_study_studyelements'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPrivateElements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('heading', models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Элементы частные Занятия',
                'verbose_name_plural': 'Элементы частные Занятия',
                'ordering': ['pk'],
            },
        ),
        migrations.RenameModel(
            old_name='StudyElements',
            new_name='StudyGroupElements',
        ),
        migrations.AlterModelOptions(
            name='studygroupelements',
            options={'ordering': ['pk'], 'verbose_name': 'Элементы групповые Занятия', 'verbose_name_plural': 'Элементы групповые Занятия'},
        ),
    ]
