# Generated by Django 3.0.8 on 2020-08-02 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20200801_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='heading_teachers',
            field=models.CharField(default=1, max_length=200, verbose_name='Заголовок учителя'),
            preserve_default=False,
        ),
    ]
