# Generated by Django 3.0.8 on 2020-08-01 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counter',
            options={'ordering': ['pk'], 'verbose_name': 'Элементы счетчика', 'verbose_name_plural': 'Элементы счетчика'},
        ),
        migrations.AlterModelOptions(
            name='homepageclasses',
            options={'ordering': ['pk'], 'verbose_name': 'Элементы классов', 'verbose_name_plural': 'Элементы классов'},
        ),
        migrations.AlterModelOptions(
            name='homereasons2',
            options={'verbose_name': 'Раздел Почему все же мы', 'verbose_name_plural': 'Раздел Почему все же мы'},
        ),
        migrations.AlterModelOptions(
            name='reasons',
            options={'ordering': ['pk'], 'verbose_name': 'Элементы раздела 5 причин', 'verbose_name_plural': 'Элементы раздела 5 причин'},
        ),
        migrations.AlterModelOptions(
            name='reasons2',
            options={'ordering': ['pk'], 'verbose_name': 'Элементы раздела почему все же мы', 'verbose_name_plural': 'Элементы раздела почему все же мы'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['name'], 'verbose_name': 'Элементы слайдера', 'verbose_name_plural': 'Элементы слайдера'},
        ),
    ]
