# Generated by Django 3.0.8 on 2020-08-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200801_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Наименование'),
        ),
    ]
