# Generated by Django 3.0.8 on 2020-08-02 11:34

from django.db import migrations, models
import faicon.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_counter_counter_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('heading', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('button_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Текст кнопки')),
                ('img', models.ImageField(blank=True, upload_to='', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Классы',
                'verbose_name_plural': 'Классы',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('heading', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('heading2', models.CharField(blank=True, max_length=200, verbose_name='Заголовок2')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('img', models.ImageField(blank=True, upload_to='', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Отзывы',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['pk'],
            },
        ),
        migrations.RenameModel(
            old_name='HomeAbout',
            new_name='About',
        ),
        migrations.DeleteModel(
            name='HomeClasses',
        ),
        migrations.DeleteModel(
            name='HomeCounter',
        ),
        migrations.DeleteModel(
            name='HomePageClasses',
        ),
        migrations.DeleteModel(
            name='HomeReasons1',
        ),
        migrations.DeleteModel(
            name='HomeReasons2',
        ),
        migrations.DeleteModel(
            name='Reasons2',
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'О нас', 'verbose_name_plural': 'О нас'},
        ),
        migrations.AlterModelOptions(
            name='counter',
            options={'ordering': ['pk'], 'verbose_name': 'Счетчик', 'verbose_name_plural': 'Счетчик'},
        ),
        migrations.AlterModelOptions(
            name='reasons',
            options={'ordering': ['pk'], 'verbose_name': 'Причины', 'verbose_name_plural': 'Причины'},
        ),
        migrations.AddField(
            model_name='counter',
            name='heading',
            field=models.CharField(default=1, max_length=200, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reasons',
            name='icon',
            field=faicon.fields.FAIconField(blank=True, max_length=50, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='reasons',
            name='img',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='reasons',
            name='text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Текст'),
        ),
    ]
