# Generated by Django 3.0.8 on 2020-08-02 12:29

from django.db import migrations, models
import faicon.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200802_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['name'], 'verbose_name': 'Слайдер', 'verbose_name_plural': 'Слайдер'},
        ),
        migrations.AlterField(
            model_name='counter',
            name='counter_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='counter',
            name='heading',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='counter',
            name='icon',
            field=faicon.fields.FAIconField(blank=True, max_length=50, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='counter',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='counter',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Число'),
        ),
        migrations.AlterField(
            model_name='counter',
            name='text',
            field=models.CharField(blank=True, max_length=50, verbose_name='Текст'),
        ),
    ]
